### PR TITLE
Decent changes to the API. Check the test/dog_model.coffee for example

### PR DESCRIPTION
**Pull request by robguthrie**

### CODE REVIEW

**Comment by robguthrie** [comment]
only half way done. Highlights include the relationships: block and the nice to use hasMany and belongsTo functions.

Next I'm going to move http request stuff from the model to the recordsInterface

**Comment by ahdinosaur** [comment]
by the way, "changes to the API" [according to semver](http://semver-ftw.org/) means this will be released as version `2.0.0` (i.e. a major bump).

**Comment by robguthrie** [comment]
thanks!

**Comment by gdpelican** [comment]
Er, we're not actually making changes to the API, right?

**Comment by robguthrie** [comment]
not the HTTP api... just the programming api

**Pull request merged**
