### PR TITLE
Base model patch

### PR DESCRIPTION
**Pull request by euglazer**

### CODE REVIEW

**Comment by robguthrie** [comment]
merged?

**Comment by gdpelican** [comment]
Whoa, I'm pretty unconvinced this is the right fix here. Can we talk about this stuff before you merge it in @euglazer? Loomio's using this thing as well.

**Comment by gdpelican** [comment]
Also one of the main arguments for rebasing pull requests is to avoid commits like 5125501 / 1f40658, which add a bunch of lines to the history without actually doing anything.

**Comment by robguthrie** [comment]
Yea.. I was a little surprised you merged this eugene, but no worries we
can work something out. I think this highlights that we should be using
forks and pull requests for everything, and not give merge permission out
to people.

James, I was the one who suggested this approach for Eugene when we
discovered the Loomio reference in the library. Cobudget does not bootstrap
the same way Loomio does so we don't have a list of permitted params at
application init. Do you have another suggested approach?

**Comment by ahdinosaur** [comment]
> Loomio's using this thing as well.

Loomio is [using a specific version tag](https://github.com/loomio/loomio/blob/master/lineman/package.json#L11), this merge won't break anyone, but that being said @euglazer it's recommended to get some feedback from other stakeholders before merging (you can always reference a commit hash as a package version regardless of whether it's in master).

---

regarding the actual PR content, why not [inject the config](https://github.com/loomio/angular_record_store/blob/1f406586b6ec0bf363b4f0e69043a87e6068101a/base_model.coffee#L3)? seems really weird to monkey patch the constructor, almost as weird as globals. :stuck_out_tongue_winking_eye:

**Comment by ahdinosaur** [comment]
> I think this highlights that we should be using
forks and pull requests for everything, and not give merge permission out
to people.

:-1: to this approach, as you then enforce yourself as the bottleneck in any development, unless that's your intention. the alternatives are [OPEN open source](http://openopensource.org/), [C4](http://rfc.zeromq.org/spec:22), and [bazaar](http://www.catb.org/~esr/writings/cathedral-bazaar/cathedral-bazaar/) -style development which usually recommend various flavors of the opposite.

**Comment by ahdinosaur** [comment]
ah disregard my comment on the PR content, [after seeing this feature in use](https://github.com/cobudget/cobudget-ui/pull/226/files#diff-87ac2baa3a16966d70769d4518468cb3R7) now i understand that injecting makes no sense and this PR makes a good deal of sense. :sweat_smile:

**Comment by gdpelican** [comment]
Not saying this will break Loomio, but having an unreviewed upstream commit
that could is not a situation I want to be in; clearly we need some sort of
process improvement (probably around cross-team code review; maybe a thumbs
up from 1 person on each side before merge?) here in order to prevent this
from happening again, for collaboration and blood pressure's sake, if
nothing else.

After having a think, I'm happier with this change than my initial
reaction, although it is a change in behaviour from before, because it
means that everything that you serialize out, is included when you
create/update it back in... (before, for example, you could serialize out
someone's email address even if it wasn't part of the permitted params, and
not worry about it coming back with the serialized version of the model on
update...) I'm currently thinking that strong_parameters on the server side
should take care of any issues this might cause, but I'm not 100% certain
whether there was a reason we made this distinction or not.

@mikey, I don't think that's how attributeNames is intended to be used;
we've been scraping the attributes from the record which comes back, so if
you serialized out { bucket: { field_a: 'a', field_b: 'b' } }, you get
'field_a' and 'field_b' added to the attribute names through
scrapeAttributeNames. We don't define attributeNames on the model anywhere
in Loomio, I don't think.

**Pull request merged**
