### PR TITLE
Make upload more flexible

### PR DESCRIPTION
**Pull request by gdpelican**

### CODE REVIEW

**Comment by robguthrie** [comment]
could you also bump the version. this seems like an interface change. is there any way we can still support using the default onSuccess, onFailure actions?

**Comment by gdpelican** [comment]
Yeah, I want to play with this more to get it right.

**Comment by gdpelican** [comment]
There's an annoying and subtle difference between the `success` callback and the `then` method, which is that `then` accepts the response as an argument, while success only gives you response.data. 

```
then(function(response) { return response.data.attachments })
```
```
success(function(data) { return data.attachments })
```

So passing `@onSuccess` to `success` doesn't work right. Of course, `then` doesn't account for the abort or progress actions... maybe there's a hybrid approach that will work.

**Comment by gdpelican** [comment]
I've updated this to keep the same interface. Keen to publish to npm so I can test 'er out on clone.

**Pull request merged**
