### PR TITLE
add BaseRecordsInterface#all

### PR DESCRIPTION
**Pull request by data-doge**
eyy loomio whatup

small PR -- added an `all` method similar to `ActiveRecord::Base`s `all` to `BaseRecordsInterface`

### CODE REVIEW

**Comment by gdpelican** [comment]
Would ya mind bumping the version as well? (I suppose per Mikey's comment [here](https://github.com/loomio/angular_record_store/pull/7) it's a minor version bump to 2.4.0)

**Comment by data-doge** [comment]
@gdpelican 

mhm done !

**Comment by gdpelican** [comment]
PS it seems somewhat likely to me that I've broken newer versions of this with the attempted ng-file-upload upgrade, so if you have some problems with it reverting these commits might be a good idea:

https://github.com/loomio/angular_record_store/commit/dec1f3dc17109f9f8f49f8841be7923ca26debe8
https://github.com/loomio/angular_record_store/commit/242bb6c2b759f6f2c1e6b767334521c77a13df82

**Comment by data-doge** [comment]
@gdpelican 

eyyy when u have a free moment could u publish this to npm?

**Comment by gdpelican** [comment]
You can actually publish yourself! Npm is great!

I'll grab it later today if you haven't yet though.

**Comment by data-doge** [comment]
hmm when i try i get

```
npm ERR! You do not have permission to publish 'angular_record_store'. Are you logged in as the correct user? : angular_record_store
```

i don't think i have push access to `loomio/angular_record_store`

**Comment by gdpelican** [comment]
Whoops! I've published 2.4.0. If you let me know what your npm username is,
I'll add ya as an owner so you can publish as well.

**Comment by data-doge** [comment]
`data-doge`

thx dude!

**Pull request merged**
